#!/usr/bin/env bash
set -x
BUILD_DIR=.build
BUILD_TYPE=Release

CONAN_PROFILE=default
if [[ "${BUILD_TYPE}" == "Debug" ]]; then
    CONAN_PROFILE="debug"
fi

conan install . -of ${BUILD_DIR} -pr ${CONAN_PROFILE} --build missing
source ${BUILD_DIR}/conanbuild.sh

cmake -H. -B${BUILD_DIR} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}\
    -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake --no-warn-unused-cli
cmake --build ${BUILD_DIR}
