#!/usr/bin/env bash
set -x
CXX=clang++
CC=clang
#CXX=g++
#CC=gcc
BUILD_DIR=.build
BUILD_TYPE=Release

CONAN_PROFILE=default
if [[ "${BUILD_TYPE}" == "Debug" ]]; then
    CONAN_PROFILE="debug"
fi

conan install . -of ${BUILD_DIR} -pr ${CONAN_PROFILE} --build missing
source ${BUILD_DIR}/build/${BUILD_TYPE}/generators/conanbuild.sh

cmake -H. -B${BUILD_DIR} -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
    -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CC_COMPILER=${CC} \
    -DCMAKE_TOOLCHAIN_FILE=${BUILD_DIR}/build/${BUILD_TYPE}/generators/conan_toolchain.cmake

cmake --build ${BUILD_DIR}
